const ActionTypes = {
   CATERGORY_LIST: "CATERGORY_LIST",
   CUEERNT_USER: "CUEERNT_USER",
   CUEERNT_CATEGORY: "CUEERNT_CATEGORY",
   SERVICES_KEY: "SERVICES_KEY",
   CHOSE_CATEGORY: "CHOSE_CATEGORY",
   CHOSE_SERVICE: "CHOSE_SERVICE",
   MY_ORDERS: "MY_ORDERS",
   ACCEPTED_ORDER: "ACCEPTED_ORDER",
   FINISHED_ORDER: "FINISHED_ORDER",
   MY_RATTING: "MY_RATTING",
   MY_RATTINGFOR_PROFILE: "MY_RATTINGFOR_PROFILE",
   ALL_WORKERS: "ALL_WORKERS",
   MESSAGE_LIST: "MESSAGE_LIST"
}

export default ActionTypes