const ActionTypes = {

   CATERGORY_LIST: "CATERGORY_LIST",
   CUEERNT_USER:"CUEERNT_USER",
   CUEERNT_CATEGORY:"CUEERNT_CATEGORY",
   SERVICES_KEY:"SERVICES_KEY",
   CHOSE_CATEGORY:"CHOSE_CATEGORY",
   CHOSE_SERVICE:"CHOSE_SERVICE",
   MY_ORDERS:"MY_ORDERS"

}

export default ActionTypes